# Pre-commit hooks for Bemo iOS app
repos:
  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint
        language: system
        files: \.swift$
        pass_filenames: false
        
      - id: no-commit-to-main
        name: Don't commit to main branch
        entry: bash -c 'if [[ $(git symbolic-ref --short HEAD) == "main" ]]; then echo "Direct commits to main branch are not allowed. Please create a feature branch."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true
        
      - id: check-xcconfig
        name: Check for example configs
        entry: bash -c 'for f in Bemo/Config/*.xcconfig; do if [[ ! -f "$f.example" ]]; then echo "Missing example config for $f"; exit 1; fi; done'
        language: system
        pass_filenames: false
        files: \.xcconfig$