# SwiftLint configuration for Bemo iOS app

# Rule configuration
opt_in_rules:
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - trailing_whitespace # Can be annoying during development
  - todo # We want to allow TODOs
  - line_length # We'll be lenient on line length for now

# Configurable rules
type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - dx
    - dy
    - tx
    - ty
    - a
    - b
    - c
    - d
    - r
    - g

# Path configuration
excluded:
  - Pods
  - vendor
  - .build
  - DerivedData
  - Bemo.xcodeproj
  - BemoTests
  - supabase

# Custom rules
custom_rules:
  mark_without_colon:
    regex: '//\s*MARK[^:]*$'
    message: "MARK comments should include a colon (:)"
    severity: warning

  force_https:
    regex: 'http://(?!localhost|127\.0\.0\.1)'
    message: "Use HTTPS instead of HTTP for external URLs"
    severity: warning

  no_print_statements:
    regex: '\bprint\('
    message: "Use proper logging instead of print statements"
    severity: warning
    excluded:
      - "*/Debug/*"
      - "*/Tests/*"